// Generate src/icons.ts — an inlined subset of Ionicons.
//
// The device is offline: no CDN, no <ion-icon> web component, no runtime
// fetch. Bundling only the icons actually used keeps the payload small and
// makes a missing icon a BUILD failure rather than a blank square in the
// field.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SVG = join(here, "..", "node_modules", "ionicons", "dist", "svg");

// Keep in sync with Hub.APPS in tracerd/tracerd/hub.py and the chrome.
const NAMES = [
  // launcher tiles
  "pulse", "scan", "recording", "cloud-upload", "wifi", "terminal",
  "document-text", "swap-vertical", "server", "location", "checkbox", "settings",
  // chrome
  "battery-half", "battery-full", "battery-dead", "chevron-forward",
  "alert-circle", "checkmark-circle", "sync-outline", "warning-outline",
  // settings groups that are not launcher apps
  "time", "globe-outline", "search",
];

const out = {};
const missing = [];
for (const n of NAMES) {
  const p = join(SVG, `${n}.svg`);
  if (!existsSync(p)) { missing.push(n); continue; }
  // Strip the outer <svg> wrapper; we re-wrap with our own sizing and
  // currentColor so icons inherit colour from CSS.
  const raw = readFileSync(p, "utf8");
  const inner = raw.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "").trim();
  out[n] = inner.replace(/\s+/g, " ");
}

if (missing.length) {
  console.error("Missing ionicons: " + missing.join(", "));
  process.exit(1);
}

const ts = `// GENERATED by scripts/gen-icons.mjs — do not edit.
// Offline Ionicons subset. Run \`npm run icons\` after changing the list.
export const ICONS = ${JSON.stringify(out, null, 2)};

export function icon(name, size = 16, color = "currentColor") {
  const body = ICONS[name];
  if (!body) return "";
  // Set \`color\` and fill="currentColor" rather than hardcoding fill/stroke:
  // Ionicons SOLID glyphs inherit fill, while OUTLINE glyphs carry their own
  // inline fill="none" stroke="currentColor". Driving both through the CSS
  // color property is the only way one wrapper serves both correctly —
  // forcing a stroke attribute here visibly thickens the solid icons.
  return \`<svg viewBox="0 0 512 512" width="\${size}" height="\${size}" fill="currentColor" style="display:block;flex-shrink:0;color:\${color}">\${body}</svg>\`;
}
`;
writeFileSync(join(here, "..", "src", "icons.js"), ts);
console.log(`wrote src/icons.js — ${Object.keys(out).length} icons`);
